### ISSUE TITLE
The 'Edit me on Github' link gives 404

### ISSUE THREAD

**Issue by yatesco** [borgbackup/borgbackup.github.io#6] opened 2015-12-22 01:11 UTC
Steps:
 - Go to http://borgbackup.readthedocs.org
 - Click on the 'Edit me on Github' link
 - view the groovy github 404

**Comment by ThomasWaldmann** [comment] 2015-12-22 01:30
duplicate of https://github.com/borgbackup/borg/issues/451

**Closed by ThomasWaldmann** 2015-12-22 01:30 UTC
